Repository apache/maven-verifier, pull requests merged in 2022-03, with the labels that each got.

#8 fix Jira link
  pom.xml
Labels: documentation

#10 fix Jenkins link
  pom.xml
Labels: documentation

#6 [MSHARED-1015] correctly set system property
  pom.xml
  src/main/java/org/apache/maven/it/Embedded3xLauncher.java
  src/test/java/org/apache/maven/it/Embedded3xLauncherTest.java
  src/test/java/org/apache/maven/it/ForkedLauncherTest.java
Labels: bug

#21 [MSHARED-1048] Upgrade junit from 4.13.1 to 4.13.2
  pom.xml
Labels: dependencies
